### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jonathanyeong** [llamatuts/llamatuts#13]
The readme is empty at the moment. I think it might be handy to have a README.  This should have:
- information about building the project and deploying onto Github pages
- Maybe style guides?
- Overall goal/timeline of the project
- Maybe our vision/tag line for the project (which will be used in the about us page).
- Information on when to merge to master.

What do you guys think?

**Comment by HazelGrant** [comment]
Think this is solid. Particularly reminders about procedures that may only happen every once in awhile, links to resources that we find ourselves referencing a lot? A good README is its own awesome resource.

**Comment by jonathanyeong** [comment]
Fantabulous, I'll work on it tonight. Please feel free to change anything I
put in :).

**Comment by jonathanyeong** [comment]
Commit 603bd2454009fdfd8d4d03d2503e0212e01ebc74 closes this issue.

**Comment by jonathanyeong** [comment]
I didn't think we needed a style guide but we may want to put one in when we actually start writing. If you want to talk about what I've added then I'm more than happy to open this issue up again.
